server:
    address: 127.0.0.1
    servlet.context-path: /
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.3.152:3306/testdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql #指定数据库类型
    hibernate:
      ddl-auto: update
